const ACCESS_KEY_ID = process.env.ACCESS_KEY_ID;
const SECRET_ACCESS_KEY = process.env.SECRET_ACCESS_KEY;
const BUCKET_REGION = process.env.BUCKET_REGION;
const BUCKET_NAME = process.env.BUCKET_NAME;
export { ACCESS_KEY_ID, SECRET_ACCESS_KEY, BUCKET_REGION, BUCKET_NAME };
